OPAutotech/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite import urls, views 
from accounts import views as v

from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.conf.urls import url
import mysite
import debug_toolbar

from django.contrib import admin

admin.site.site_header = 'OPAUTOTECH'                    # default: "Django Administration"
admin.site.index_title = 'Features area'                 # default: "Site administration"
admin.site.site_title = 'Adminsitration' # default: "Django site admin"
urlpatterns = [
    path('', include('mysite.urls', namespace='mysite')),
    path('admin/', admin.site.urls),
    path("register/", v.register, name="register"),
    path('', include("django.contrib.auth.urls")),
    url(r'^__debug__/', include(debug_toolbar.urls)),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'mysite.views.custom_page_not_found_view'
handler500 = 'mysite.views.custom_error_view'
handler403 = 'mysite.views.custom_permission_denied_view'
handler400 = 'mysite.views.custom_bad_request_view'

mysite/urls.py
from mysite.models import Painting
from django.urls import path
from mysite import views
# from .views import DrawingDetail
app_name = 'mysite'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('reportTable/',views.reportTable, name= 'reportTable'),
    path('realtimeReport/',views.realtimeReport, name='realtimeReport'),
    
    path('jobTable',views.jobTable, name= 'jobTable'),
    path('jobReport/<str:job_id>', views.jobReport, name='jobReport'),
    path('createJob',views.createJob),
    path('jobTable/edit/<str:job_id>',views.editJob),
    path('jobTable/update/<str:job_id>',views.updateJob),
    path('jobTable/delete/<str:job_id>',views.deleteJob),



    path('drawingTable/<str:job_id>',views.drawingTable, name='drawingTable'),
    path('createDrawing/<str:job_id>',views.createDrawing, name= 'createDrawing'),  
    path('drawingTable/<str:job_id>/edit/<str:drawing_id>',views.editDrawing),
    path('drawingTable/<str:job_id>/update/<str:drawing_id>',views.updateDrawing),
    path('drawingTable/<str:job_id>/delete/<str:drawing_id>',views.deleteDrawing),



    path('workflow/<str:drawing_id>',views.workflow, name= 'workflow'),

    path('createDocument/<str:drawing_id>',views.createDocument, name= 'createDocument'),
    path('workflow/<str:drawing_id>/edit/document/<int:document_id>',views.editDocument),
    path('workflow/<str:drawing_id>/update/document/<int:document_id>',views.updateDocument),
    path('workflow/<str:drawing_id>/delete/document/<int:document_id>',views.deleteDocument),


    path('createMaker/<str:drawing_id>',views.createMaker, name='createMaker'),
    path('workflow/<str:drawing_id>/edit/maker/<int:maker_id>',views.editMaker),
    path('workflow/<str:drawing_id>/update/maker/<int:maker_id>',views.updateMaker),
    path('workflow/<str:drawing_id>/delete/maker/<int:maker_id>',views.deleteMaker),


    path('createCutting/<str:drawing_id>',views.createCutting, name='createCutting'),
    path('workflow/<str:drawing_id>/edit/cutting/<int:cutting_id>',views.editCutting),
    path('workflow/<str:drawing_id>/update/cutting/<int:cutting_id>',views.updateCutting),
    path('workflow/<str:drawing_id>/delete/cutting/<int:cutting_id>',views.deleteCutting),



    path('createMachine/<str:drawing_id>',views.createMachine, name='createMachine'),
    path('workflow/<str:drawing_id>/edit/machine/<int:machine_id>',views.editMachine),
    path('workflow/<str:drawing_id>/update/machine/<int:machine_id>',views.updateMachine),
    path('workflow/<str:drawing_id>/delete/machine/<int:machine_id>',views.deleteMachine),



    path('createQc/<str:drawing_id>',views.createQc, name='createQc'),
    path('workflow/<str:drawing_id>/edit/qc/<int:qc_id>',views.editQc),
    path('workflow/<str:drawing_id>/update/qc/<int:qc_id>',views.updateQc),
    path('workflow/<str:drawing_id>/delete/qc/<int:qc_id>',views.deleteQc),


    path('createPainting/<str:drawing_id>',views.createPainting, name='createPainting'),
    path('workflow/<str:drawing_id>/end/painting/<int:painting_id>',views.endPainting),
    path('workflow/<str:drawing_id>/edit/painting/<int:painting_id>',views.editPainting),
    path('workflow/<str:drawing_id>/update/painting/<int:painting_id>',views.updatePainting),
    path('workflow/<str:drawing_id>/delete/painting/<int:painting_id>',views.deletePainting),


    path('createQcPainting/<str:drawing_id>',views.createQcPainting, name='createQcPainting'),
    path('workflow/<str:drawing_id>/edit/qcpainting/<int:qcpainting_id>',views.editQcPainting),
    path('workflow/<str:drawing_id>/update/qcpainting/<int:qcpainting_id>',views.updateQcPainting),
    path('workflow/<str:drawing_id>/delete/qcpainting/<int:qcpainting_id>',views.deleteQcPainting),


    path('createAssembly/<str:drawing_id>',views.createAssembly, name='createAssembly'),
    path('workflow/<str:drawing_id>/edit/assembly/<int:assembly_id>',views.editAssembly),
    path('workflow/<str:drawing_id>/update/assembly/<int:assembly_id>',views.updateAssembly),
    path('workflow/<str:drawing_id>/delete/assembly/<int:assembly_id>',views.deleteAssembly),

    path('createRevise/<str:drawing_id>',views.createRevise, name='createRevise'),
    path('workflow/<str:drawing_id>/edit/revise/<int:revise_id>',views.editRevise),
    path('workflow/<str:drawing_id>/update/revise/<int:revise_id>',views.updateRevise),
    path('workflow/<str:drawing_id>/delete/revise/<int:revise_id>',views.deleteRevise),

    path('uploadFile/<str:drawing_id>',views.uploadFile, name='uploadFile'),
    path('workflow/<str:drawing_id>/delete/file/<int:file_id>',views.deleteFile),

    path('uploadAssemblyFile/<str:job_id>',views.uploadAssemblyFile, name='uploadAssemblyFile'),
    path('drawingTable/<str:job_id>/delete/assemblyfile/<int:assemblyfile_id>',views.deleteAssemblyFile),

    path('uploadPlanFile/<str:job_id>',views.uploadPlanFile, name='uploadPlanFile'),
    path('drawingTable/<str:job_id>/delete/planfile/<int:planfile_id>',views.deletePlanFile),

    path('uploadModelFile/<str:job_id>',views.uploadModelFile, name='uploadModelFile'),
    path('uploadModelFile/<str:job_id>/modelfile/<int:modelfile_id>/delete/deletepdfFile/',views.deletepdfFile),
    path('uploadModelFile/<str:job_id>/modelfile/<int:modelfile_id>/delete/deleteEdrawingFile/',views.deleteEdrawingFile),

    path('workflow',views.flowSearch, name='flowSearch')
]

templates/createDrawing.html
{% extends 'layout.html' %}
{% load widget_tweaks %}

{% block content %}
{% if user.is_authenticated%}
<h2 align="center">Drawing of {{get_job_id.jobNo}}</h2>
<form method="POST">
    {% csrf_token %}
    <h2 align="center">{{ Drawing.job}}</h2>
    <div class='form-group'>
        
        <lable for="exampleFormControlSelect1">Select job No.</lable>

        {% render_field form.job class="form-control" %}
        
    </div>

    <div class="form-group">
        <lable for="">Drawing No.</lable>

        {% render_field form.drawingNo class="form-control" %}
    </div>

    <div class="form-group">
        <lable for="">Drawing Description</lable>

        {% render_field form.drawingDesc class="form-control" %}
    </div>


    <div class="form-group">
        <lable for="">Drawing quantity</lable>

        {% render_field form.Quantity class="form-control" %}
    </div>

    <h1></h1>
    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
        This [Drawing No] are already exists!
      </div>
    {% endif %}
    <input type="submit" class="btn btn-primary">

</form>

{% else %}
    <h1 align="center">You need to login first </h1>

{% endif %}
{% endblock %}

templates/createJob.html
 {% extends 'layout.html' %}
{% load widget_tweaks %}

{% block content %}
{% if user.is_authenticated%}
<h2 align="center">Create Job</h2>
<form method="POST">
    {% csrf_token %}
    <div class='form-group'>
        <lable for="">Job No.</lable>

        {% render_field form.jobNo class="form-control" %}
    </div>

    <div class="form-group">
        <lable for="">Project Name</lable>

        {% render_field form.projectName class="form-control" %}
    </div>

    <div class="form-group">
        <lable for="">Project Description</lable>

        {% render_field form.projectDesc class="form-control" %}
    </div>

    <h1></h1>
    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
        This [Job No] are already exists!
      </div>
    {% endif %}
    <input type="submit" class="btn btn-primary">

</form>









{% else %}
    <h1 align="center">You need to login first </h1>

{% endif %}
{% endblock %}




















<!-- <DOCTYPE html>
<html lang="en">
<head>
    <mate charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django</title>
</head>
<body>
        <h2>{{ text1 }}</h2>
        <h2>{{ text1 }}</h2>

        <h2>tags</h2>
        {% for tag in tag %}
            <p> {{tag}}  </p>
        {% endfor %}

        <ul>
        <h1>hello</h1>
            {% for tag in tag %}
            <li> {{tag}}  </li>
        {% endfor %}
        </ul>

        <h2>hi</h2>
        {% if rating > 3 %}
            <h3> morethan 3</h3>
        {% else %}
        <h3> lessthan 3 </h3>
        {% endif %}
</body>
</html> -->

templates/flowsearch.html
{% extends 'layout.html' %}

{% block content %}

<DOCTYPE html>
  <html lang="en">
    <head>
      <mate charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Jobs | OP AUTOTECH</title>
  </head>
<body>
{% if user.is_authenticated%}

  <div class="container-lg">
    <div class="table-responsive">
      <div class="table-wrapper">
        <div class="table-title">
          <div align="center" class="work-flow"><h1>WorkFlow <b>Search</b></h1></div>
        

    <lable style="margin-left: 25px;">Search and select drawing number</lable>
    <div class="wrap-input100 validate-input">
        <input class="input100 form-control" list="brow" id="Search" placeholder="Search" required>
        <span class="focus-input100"></span>
        <span class="symbol-input100">
            <i class="fa fa-search" aria-hidden="true"></i>
        </span>
        <datalist id="brow">
          {% for drawing in drawing %}
          <option value="{{drawing}}">
          {% endfor %}
        </datalist> 
    </div>


    <input onclick="myFunction()" type="button" role="button" class="btn btn-success" name="myButton" href='/workflow/' value="Search">


        </div>
    </div>
</div>     



{% else %}
    <h1 align="center"><a href="/login" >You need to login first</a></h1>
{% endif %}

<script>
  function myFunction() {
    var x = document.getElementById("Search").value;
    location.href = "/workflow/"+x;
    
      }
  
  </script>

</body>
</html>
{% endblock %}

templates/home.html
{% extends 'layout.html' %}

{% block content %}

<DOCTYPE html>
<html lang="en">
<head>
    <mate charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home | OP AUTOTECH</title>
</head>
<body class="bg">
    
        <div class="home">
            <h>OP AUTOTECH</h>
            <p class="mb-5 fs-lg-1  aos-init aos-animate" data-aos="fade-down" data-aos-delay="50" data-aos-duration="1000" style="color:gray;">WEB DATABASE</p>
            <div class="row justify-content-center">
                {% if user.is_authenticated%}
                    <div class="col-auto">
                        <a href="/jobTable" class="btn btn-success" style="width: 160px;">PROJECTS</a>
                    </div>
                    <div class="col-auto">
                        <a href="/reportTable" class="btn btn-light" style="width: 160px;">REPORTS</a>
                    </div>
                {% else %}
                    <div class="col-auto">
                        <a href="/login" class="btn btn-success" style="width: 150px;">LOGIN</a>
                    </div>
                    <div class="col-auto">
                        <a href="/register" class="btn btn-light" style="width: 150px;">REGISTER</a>
                    </div>
                {% endif %}
            </div>
        </div>

    </body>
    </html>
{% endblock %}

templates/layout.html
<DOCTYPE html>
    <html lang="en">
    <head>
      {% load static %}
      
        <mate charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        
        <!--===============================================================================================-->	
        <link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}"/>
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <!--===============================================================================================-->
    </head>
    <body>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="/">OP AUTOTECH</a>
      
        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="/" style="text-align: left;">HOME</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'mysite:jobTable' %}" style="text-align: left;">JOB</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'mysite:flowSearch' %}" style="text-align: left;">WORKFLOW</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'mysite:reportTable' %}" style="text-align: left;">REPORT</a>
            </li>
            </li>
          </ul>
          
          <div class="nav-item dropdown" style="margin-top: 5px; margin-bottom: 5px; margin-right: 40px; text-align: left;">
            {% if user.is_authenticated%}
              <a class="text-white bg-dark dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Hello, {{user.username}}
              </a>
              
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink" style="min-width: 135px;">
                {% if user.is_superuser%}
                <a class="dropdown-item" href="/admin">Admin Page</a>
                {% endif %}
                <a class="dropdown-item" href="/realtimeReport">Real-time</a>
                <a class="dropdown-item" href="/logout">Logout</a>
              </div>
            {% else %}
              <a href="/login" class="btn btn-outline-success" role="button" aria-pressed="true">Login</a>
            {% endif %}
          </div>
          
            
        </div>
        
      </nav>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <script type="text/javascript" src="https://unpkg.com/xlsx@0.15.1/dist/xlsx.full.min.js"></script>
        <script src="{% static 'js/downloadFile.js' %}"></script>
        
        <!--===============================================================================================-->	

        <!--===============================================================================================-->
          
        <script src="{% static 'js/main.js' %}"></script>
        <!--===============================================================================================-->
        <script src="{% static 'vendor/select2/select2.min.js' %}"></script>
        <!--===============================================================================================-->
        <script src="{% static 'vendor/tilt/tilt.jquery.min.js' %}"></script>
          
        <script src="{% static 'js/sort-table.js' %}"></script>
        <script >
          $('.js-tilt').tilt({
            scale: 1.1
          })
        </script>
        <!--===============================================================================================-->
          
        
        {% block content %} 
        
        {% endblock %}
    </body>
    </html>

templates/uploadModelFile.html
{% extends 'layout.html' %}
{% load widget_tweaks %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <mate charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>3D-Model Files | OP AUTOTECH</title>
</head>
<body>
<div class="table-wrapper">
{% if user.is_authenticated%}
<h2 align="center" style="margin-bottom: 20px;">3D-Model Files of {{get_job_id}}</h2>
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Home</a></li>
      <li class="breadcrumb-item"><a href="{% url 'mysite:jobTable' %}">Jobs</a></li>
      <li class="breadcrumb-item"><a href="{% url 'mysite:drawingTable' job_id=get_job_id %}">Drawings</a></li>
      <li class="breadcrumb-item active" aria-current="page">3D-Model Files</li>
    </ol>
  </nav>
<form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    <p hidden>{% render_field form.user class="form-control"%}</p>
    <div class='form-group'>
        <p hidden><lable for="exampleFormControlSelect1">job No.</lable>
        {% render_field form.job class="form-control" %}</p> 
    </div>

    {% if not get_modelfile_id.filepdf %}
        {% if request.user.groups.all.0.name == 'Design' or request.user.groups.all.1.name == 'Design' or request.user.groups.all.2.name == 'Design' or request.user.groups.all.3.name == 'Design' or request.user.groups.all.4.name == 'Design' or request.user.groups.all.5.name == 'Design' or request.user.groups.all.6.name == 'Design' or request.user.groups.all.7.name == 'Design' or user.is_staff or request.user.groups.all.0.name == 'Document' or request.user.groups.all.1.name == 'Document' or request.user.groups.all.2.name == 'Document' or request.user.groups.all.3.name == 'Document' or request.user.groups.all.4.name == 'Document' or request.user.groups.all.5.name == 'Document' or request.user.groups.all.6.name == 'Document' or request.user.groups.all.7.name == 'Document'%}
        <lable style="margin-left: 25px;">Upload 3D-PDF file</lable>
        <div class="input-group wrap-input100 validate-input" style="margin-left: 25px; margin-top: 15px; margin-bottom: 20px; max-width: 90%">
            <span class="input-group-btn">
                <span class="btn btn-light" style=" border-color: black;" onclick="$(this).parent().find('input[type=file]').click();">Choose File...</span>
                <input name="filepdf" onchange="$(this).parent().parent().find('.form-control').html($(this).val().split(/[\\|/]/).pop());" style="display: none;" type="file" value="get_modelfile_id.filepdf">
            </span>
            <span class="form-control"></span>
        </div>
        {% endif %}
    {% else %}
        <lable style="margin-left: 25px;">Download 3D-PDF file</lable>
        <div class="input-group wrap-input100 validate-input" style="margin-left: 25px; margin-top: 15px; margin-bottom: 20px; max-width: 90%">
        <a href="{{ get_modelfile_id.filepdf.url }}" class="btn btn-primary"  role="button"target="_blank" rel="noopener noreferrer">Download 3D-Model File</a>       
        {% if user.is_staff %}
            <a class="delete" title="Delete" data-toggle="tooltip" href='{{get_job_id}}/modelfile/{{get_modelfile_id.id}}/delete/deletepdfFile' onclick="return confirm('Are you sure you want to delete this item?');">
            <i class="material-icons fa-2x" style="margin-top: 5px;">&#xE872;</i></a>
        {% endif %}
        </div>
    {% endif %}

    {% if not get_modelfile_id.fileEdrawing %}
        {% if request.user.groups.all.0.name == 'Design' or request.user.groups.all.1.name == 'Design' or request.user.groups.all.2.name == 'Design' or request.user.groups.all.3.name == 'Design' or request.user.groups.all.4.name == 'Design' or request.user.groups.all.5.name == 'Design' or request.user.groups.all.6.name == 'Design' or request.user.groups.all.7.name == 'Design' or user.is_staff or request.user.groups.all.0.name == 'Document' or request.user.groups.all.1.name == 'Document' or request.user.groups.all.2.name == 'Document' or request.user.groups.all.3.name == 'Document' or request.user.groups.all.4.name == 'Document' or request.user.groups.all.5.name == 'Document' or request.user.groups.all.6.name == 'Document' or request.user.groups.all.7.name == 'Document'%}
        <lable style="margin-left: 25px;">Upload E-Drawing file</lable>
        <div class="input-group wrap-input100 validate-input" style="margin-left: 25px; margin-top: 15px; margin-bottom: 20px; max-width: 90%">
            <span class="input-group-btn">
                <span class="btn btn-light" style=" border-color: black;" onclick="$(this).parent().find('input[type=file]').click();">Choose File...</span>
                <input name="fileEdrawing" onchange="$(this).parent().parent().find('.form-control').html($(this).val().split(/[\\|/]/).pop());" style="display: none;" type="file" >
            </span>
            <span class="form-control"></span>
        </div>
        {% endif%}
    {% else %}
        <lable style="margin-left: 25px;">Download E-Drawing file</lable>
        <div class="input-group wrap-input100 validate-input" style="margin-left: 25px; margin-top: 15px; margin-bottom: 20px; max-width: 90%">
        <a href="{{ get_modelfile_id.fileEdrawing.url }}" class="btn btn-outline-primary"  role="button"target="_blank" rel="noopener noreferrer">Download E-Drawing File</a>       
        {% if user.is_staff %}
            <a class="delete" title="Delete" data-toggle="tooltip" href='{{get_job_id}}/modelfile/{{get_modelfile_id.id}}/delete/deleteEdrawingFile' onclick="return confirm('Are you sure you want to delete this item?');">
            <i class="material-icons fa-2x" style="margin-top: 5px;">&#xE872;</i></a>
        {% endif %}
        </div>
    {% endif %}

 

    {% if not get_modelfile_id.fileEdrawing or not get_modelfile_id.filepdf %}
        {% if request.user.groups.all.0.name == 'Design' or request.user.groups.all.1.name == 'Design' or request.user.groups.all.2.name == 'Design' or request.user.groups.all.3.name == 'Design' or request.user.groups.all.4.name == 'Design' or request.user.groups.all.5.name == 'Design' or request.user.groups.all.6.name == 'Design' or request.user.groups.all.7.name == 'Design' or user.is_staff or request.user.groups.all.0.name == 'Document' or request.user.groups.all.1.name == 'Document' or request.user.groups.all.2.name == 'Document' or request.user.groups.all.3.name == 'Document' or request.user.groups.all.4.name == 'Document' or request.user.groups.all.5.name == 'Document' or request.user.groups.all.6.name == 'Document' or request.user.groups.all.7.name == 'Document'%}
            <input type="submit" class="btn btn-success" name="myButton" value="Submit">
            <a href='/drawingTable/{{get_job_id}}' class='btn btn-danger' onclick="return confirm('Are you sure you want to discard your changes?');">Back</a>
            <a style="color: #c80000;">{{ form.errors }}</a>
        {% endif %}
    {% endif %}
</form>





{% else %}
    <h1 align="center"><a href="/login" >You need to login first</a></h1>
{% endif %}
</div>
</body>
</html>
{% endblock %}